### ISSUE TITLE
make an organization

### ISSUE THREAD

**Issue by ghost** [duangish/duangish.github.io#1]

**Comment by clemsos** [comment]
So far the name is "duangish" because anything else (duang, duangduang etc) was taken. Any better names ?

**Comment by ghost** [comment]
Yeah, sounds good. Should we get that domain too? keep it simple. Yes,
should be one name across the board.

**Comment by clemsos** [comment]
Well, isn't  duangish too close from anguish ? it is quite negative but that can be interesting too : we answer your wet nightmares about Chinese tech 'danguish'

**Comment by ghost** [comment]
hahaha, I like it

**Comment by clemsos** [comment]
duangish.com is up
