### ISSUE TITLE
Open social media accounts

### ISSUE THREAD

**Issue by clemsos** [duangish/duangish.github.io#12]
Twitter / Facebook page . Do we need Wechat ?

**Comment by ghost** [comment]
Yes wechat and the others.

**Comment by ghost** [comment]
And instagram

**Comment by ghost** [comment]
I changed the config to show the new name for twitter and github, better git em broooo

**Comment by clemsos** [comment]
- info@duangish.com
- https://www.facebook.com/duangish
- https://twitter.com/duangish
- https://github.com/duangish
- instagram.com @duangish

**Comment by clemsos** [comment]
We chat is tight to phone so not very easy. Need one though. Maybe a wechat organization is better

**Comment by ghost** [comment]
Yep and please send me the passes privately

**Comment by clemsos** [comment]
holy shit http://apply.wechat.com/

**Comment by clemsos** [comment]
madness

**Comment by clemsos** [comment]
we'll stick to a good old wechat group for now

**Comment by ghost** [comment]
Need a friend there is fastest

**Comment by clemsos** [comment]
deserves its own issue #17
