### ISSUE TITLE
Mobile credential avatars are crunched

### ISSUE THREAD

**Issue by ghost** [duangish/duangish.github.io#22]
Look on the phone

**Comment by clemsos** [comment]
![](https://mmi484.whatsapp.net/d/bCr3wPPgnYm9i6jfgJzJP1a1dsk/AijbI9NiGTSahNOp6Mb-sXbp5rfnihQIAS03eyGlIYCI.jpg)

**Comment by clemsos** [comment]
@rejon can you test the fix ? from 713cbe9

**Comment by ghost** [comment]
Nope

**Comment by ghost** [comment]
ok looks like we can close, except if you can reproduce  

--

Clément Renaud

[@clemsos](http://twitter.com/clemsos)  
http://clementrenaud.com

> On Feb 9 2016, at 1:54 am, Jon Phillips &lt;jon@fabricatorz.com&gt; wrote:  
> Nope

**Comment by clemsos** [comment]
haha I can comment as you with an email trick. good to know !

**Comment by clemsos** [comment]
actually no trick just a bug...

**Comment by clemsos** [comment]
can not reproduce, closing
